Merging reflSW and main
MaksimMelnik/STS-Simple-Solver pull request #3
Opened 2023-07-06 16:46 UTC by FlezZz23

2023-07-07 10:11 UTC, MaksimMelnik requested changes

2023-07-07 10:11 UTC, MaksimMelnik commented on src/R_exch.m
> +    disp("M2 and M4 must be atoms")
можно прям использовать warning('...') или error('...'), чтобы в консольке прям засветилось или исполнение скрипта прервалось при некорректном использовании

2023-07-07 10:11 UTC, MaksimMelnik commented on src/Rci.m
> +    IndexOfMolecules=containers.Map(names,index);
Ты, кажется, говорил, что этот контейнер в мейн вынес?

2023-07-07 10:11 UTC, MaksimMelnik commented on src/Rci.m
> +    VibrDeactivationOfProduct=0; % 0 - активация продукта реакции отключена
Переведи на английский, пожалуйста

2023-07-07 10:11 UTC, MaksimMelnik commented on src/Rpart_ODE_SW.m
> +R=Rci(y2, kinetics); %rpart for NO
Комментарий про NO лишний, если функция универсальна

2023-07-07 10:11 UTC, MaksimMelnik commented on src/Rpart_ODE_SW.m
> +   e_i=[e_i, kinetics.Ps{ind}.ev_i{ind_e}(1:kinetics.Ps{ind}.num_vibr_levels(1)) + kinetics.Ps{ind}.ev_0(ind_e)+...
Может налететь на ошибку, если num_vibr_levels(1), а не num_vibr_levels(ind_e)

2023-07-07 10:31 UTC, MaksimMelnik commented on src/R_diss_Aliat_onoff.m
> + ZvibT=sum(exp(-M.ev_i{i}(1:M.num_vibr_levels)/(V_K*T)));
В текущем варианте не совместимо с моими кодами с учётом электронного возбуждения. Вместо M.num_vibr_levels должно быть M.num_vibr_levels(i)

2023-07-07 10:47 UTC, MaksimMelnik commented on plots/Streicher21_O2_Ar_plots.m
> +addpath('..\data\O2_Ar Streicher experiment\');
Путь добавляется, но не удаляется затем. Лучше ниже прописывать load('..\data\O2_Ar Streicher experiment\O2Ar_Streicher_behind_ReflSW.mat'), чтобы не манипулировать с путями.

2023-07-07 11:07 UTC, MaksimMelnik commented on plots/Streicher21_O2_Ar_plots.m
> +tiledlayout(2, 2, "TileSpacing", "compact", "Padding", "tight")
В моей версии для поля "Padding" ещё нет параметра "tight". Можешь заменить, пожалуйста, для совместимости? Например, на "normal" или отказаться от этого параметра

2023-07-07 11:11 UTC, MaksimMelnik commented on plots/Streicher22_NO_plots.m
> +addpath('..\data\NO experiment\');
Ссылка устарела, ты переименовывал папку

2023-07-07 11:12 UTC, MaksimMelnik commented on plots/Streicher22_NO_plots.m
> +tiledlayout(2, 2, "TileSpacing", "compact", "Padding", "tight")
Измени параметр Padding для совместимости, пожалуйста

2023-07-07 11:17 UTC, MaksimMelnik commented on examples/NO_Streicher.m
Стоит добавить краткое описание выходного формата и что вообще является выходными данными

2023-07-07 11:18 UTC, MaksimMelnik commented on examples/NO_Streicher.m
Нужно ли делать clear all или достаточно clear dat dat1 ? Сейчас показывает варнинг на clear all

2023-07-07 11:19 UTC, MaksimMelnik commented on examples/NO_Streicher.m
38. Варнинг на разные отступы перед for и end для него. Это может путать читающего код.

2023-07-07 11:21 UTC, MaksimMelnik commented on examples/NO_Streicher.m
222. переменная out не используется

2023-07-07 11:23 UTC, MaksimMelnik commented on plots/Streicher21_O2_Ar_plots.m
> +for var=[1:9]
Варнинг на использование формата. Следует использовать 1:3 или [1 2 3]

2023-07-07 11:24 UTC, MaksimMelnik commented on plots/Streicher22_NO_plots.m
> +for var=[1:11]
Варнинг на формат определения массива

2023-07-07 11:25 UTC, MaksimMelnik commented on plots/Streicher22_NO_plots.m
> +end;
варнинг на точку с запятой

2023-07-07 16:55 UTC, FlezZz23 commented on data/O2_Ar Streicher experiment/O2_Ar_Streicher21_experiment.mat
Для чистого О2 данные, которые мы получили по переписке, но там я не строил errorbar и не сохранял данные по погрешности.

2023-07-07 17:06 UTC, FlezZz23 commented on data/particles_data_ini.m
> +val_A=[7e21, 3e22, 3e22, 3e22, 7e21, 7e21, 7e21, 7e21, 7e21, ...
добавил %Data from Park 1994

2023-07-07 17:06 UTC, FlezZz23 commented on data/particles_data_ini.m
> +NO.red_osc_mass=1.24*1e-26;
исправил

2023-07-07 17:06 UTC, FlezZz23 commented on data/particles_data_ini.m
> +val_A=[5e15, 1.1e17, 1.1e17, 1.1e17, 5e15, 5e15, 5e15, 5e15, 5e15, ...
исправил

2023-07-07 17:07 UTC, FlezZz23 commented on data/particles_data_ini.m
> +    Coll_NO_O__N_O2.ArrA(1)=8.4e12/N_a*1e-6; Coll_NO_O__N_O2.ArrN(1)=0;
Я тоже добавил и хотел использовать, но в итоге даже не использовал ни разу, мне тоже не очень понравилась эта идея

2023-07-07 17:22 UTC, FlezZz23 commented on examples/NO_Streicher.m
Окей, исправил

2023-07-07 17:58 UTC, FlezZz23 commented on examples/NO_Streicher.m
исправил

2023-07-07 17:58 UTC, FlezZz23 commented on examples/NO_Streicher.m
исправил и в целом добавил комментариев в этот файл

2023-07-07 17:59 UTC, FlezZz23 commented on plots/Streicher21_O2_Ar_plots.m
> +%%Pressure
ну вообще там строился график сравнения давления, но в целом его можно убрать, сомневаюсь что мы будем его использовать

2023-07-07 18:00 UTC, FlezZz23 commented on plots/Streicher21_O2_Ar_plots.m
> +%%Сравнение с экспериментом, графики
Ок

2023-07-07 18:01 UTC, FlezZz23 commented on plots/Streicher22_NO_plots.m
> +addpath('..\data\NO experiment\');
добавил

2023-07-07 18:03 UTC, FlezZz23 commented on src/R_diss_Aliat_onoff.m
> + ZvibT=sum(exp(-M.ev_i{i}(1:M.num_vibr_levels)/(V_K*T)));
Я немного запутался, так мне вообще убрать, чтоб осталось просто M.ev_i{i} и будем тогда просто обнулять этот массив в мейне или все таки добавить M.ev_i{i}(1:M.num_vibr_levels(i))?

2023-07-07 18:05 UTC, FlezZz23 commented on src/R_exch.m
> +    disp("M2 and M4 must be atoms")
добавил

2023-07-07 18:06 UTC, FlezZz23 commented on src/Rci.m
> +    IndexOfMolecules=containers.Map(names,index);
Исправил

2023-07-07 18:35 UTC, FlezZz23 commented on src/Rci.m
> +    VibrDeactivationOfProduct=0; % 0 - активация продукта реакции отключена
исправил

2023-07-07 18:35 UTC, FlezZz23 commented on src/Rpart_ODE_SW.m
> +R=Rci(y2, kinetics); %rpart for NO
исправил

2023-07-07 18:36 UTC, FlezZz23 commented on src/Rpart_ODE_SW.m
> +   e_i=[e_i, kinetics.Ps{ind}.ev_i{ind_e}(1:kinetics.Ps{ind}.num_vibr_levels(1)) + kinetics.Ps{ind}.ev_0(ind_e)+...
Согласен, исправил

2023-07-07 18:37 UTC, FlezZz23 commented on plots/Streicher21_O2_Ar_plots.m
> +addpath('..\data\O2_Ar Streicher experiment\');
Исправил, и в NO тоже

2023-07-07 18:39 UTC, FlezZz23 commented on plots/Streicher21_O2_Ar_plots.m
> +tiledlayout(2, 2, "TileSpacing", "compact", "Padding", "tight")
исправил, и в NO тоже

2023-07-07 18:42 UTC, FlezZz23 commented on examples/NO_Streicher.m
Matlab ругался на clear all, потому что это закрывает все функции и что-то там еще и предложил заменить это на clearvars если необходимо очистить workspace. Я так и поступил

2023-07-07 18:44 UTC, FlezZz23 commented on examples/NO_Streicher.m
Отступы пофиксил

2023-07-07 18:44 UTC, FlezZz23 commented on examples/NO_Streicher.m
убрал

2023-07-07 18:44 UTC, FlezZz23 commented on plots/Streicher21_O2_Ar_plots.m
> +for var=[1:9]
пофиксил

2023-07-07 18:45 UTC, FlezZz23 commented on plots/Streicher22_NO_plots.m
> +for var=[1:11]
исправил

2023-07-07 18:45 UTC, FlezZz23 commented on plots/Streicher22_NO_plots.m
> +end;
исправил

2023-07-08 09:51 UTC, MaksimMelnik commented on data/NO Streicher experiment/NO_behind_ReflSW.mat
Угу. Тогда стоит назвать файлы так, чтобы было понятно, что это расчётные данные.

2023-07-08 09:52 UTC, MaksimMelnik commented on data/O2_Ar Streicher experiment/O2_Ar_Streicher21_experiment.mat
Мне кажется, некорректно их публиковать в открытом доступе, раз это данные из личной переписки.

2023-07-08 11:12 UTC, MaksimMelnik commented on plots/Streicher21_O2_Ar_plots.m
> +%%Pressure
Почему нам не стоит его использовать? Это же экспериментальные данные

2023-07-08 11:15 UTC, MaksimMelnik commented on src/R_diss_Aliat_onoff.m
> + ZvibT=sum(exp(-M.ev_i{i}(1:M.num_vibr_levels)/(V_K*T)));
Давай оставим просто M.ev_i{i}. Я просто обратил внимание на баг с представленной реализацией.

2023-07-08 11:27 UTC, MaksimMelnik requested changes

2023-07-08 11:27 UTC, MaksimMelnik commented on src/Rci.m
> +    VibrDeactivationOfProduct=0; %1 - taking into ccount vibrational
Не хватает артиклей и опечатка в "account"

2023-07-08 11:27 UTC, MaksimMelnik commented on src/Rci.m
>      %если я правильно понимаю для тех кто слева надо +, а для тех кто
Можно эти комментарии убрать уже, наверное

2023-07-09 09:56 UTC, FlezZz23 commented on src/R_diss_Aliat_onoff.m
> + ZvibT=sum(exp(-M.ev_i{i}(1:M.num_vibr_levels)/(V_K*T)));
Вернул просто M.ev_i{i}, тогда в R_exch тоже везде вернуть просто M.ev_i{1}?

2023-07-09 09:58 UTC, FlezZz23 commented on src/Rci.m
> +    VibrDeactivationOfProduct=0; %1 - taking into ccount vibrational
Исправил

2023-07-09 09:58 UTC, FlezZz23 commented on src/Rci.m
>      %если я правильно понимаю для тех кто слева надо +, а для тех кто
Исправил

2023-07-09 10:01 UTC, FlezZz23 commented on examples/NO_Streicher.m
Добавил

2023-07-09 10:45 UTC, FlezZz23 commented on plots/Streicher21_O2_Ar_plots.m
> +%%Pressure
вернул график с давлением

2023-07-09 10:46 UTC, FlezZz23 commented on data/NO Streicher experiment/NO_behind_ReflSW.mat
У меня не хватает фантазии, там и так длинные названия..

2023-07-09 10:47 UTC, FlezZz23 commented on data/O2_Ar Streicher experiment/O2_Ar_Streicher21_experiment.mat
Могу заменить их на данные с графиков

2023-07-09 10:58 UTC, FlezZz23 commented on data/O2_Ar Streicher experiment/O2_Ar_Streicher21_experiment.mat
Заменил

2023-07-11 11:10 UTC, MaksimMelnik commented on data/NO Streicher experiment/NO_behind_ReflSW.mat
Мб один файл output_ReflSW_NO_Ar, а в него записать переменные с данными между волнами и после отражённой?

2023-07-11 11:49 UTC, MaksimMelnik requested changes

2023-07-11 11:49 UTC, MaksimMelnik commented on src/Rci.m
Ещё, наверное, стоит в O2 Страйкера добавить очистку переменных dat, dat1 и kinetics. Если его запустить после NO, ругается на dat, а на оставшийся старый IndexOfMolecules не ругается

2023-07-11 11:49 UTC, MaksimMelnik commented on examples/NO_Streicher.m
i_ini=1:11
лучше оставить какой-то один тесткейс для первого запуска, чтобы новый юзер не повяз в расчётах

2023-07-11 12:13 UTC, FlezZz23 commented on examples/NO_Streicher.m
Ок

2023-07-11 12:14 UTC, FlezZz23 commented on examples/NO_Streicher.m
Ну в целом, кажется, что в этих экспериментах FHO получше описывала колебательную температуру

2023-07-11 13:52 UTC, FlezZz23 commented on data/NO Streicher experiment/NO_behind_ReflSW.mat
Сделал

2023-07-11 18:24 UTC, FlezZz23 commented on src/Rci.m
Исправил

2023-07-12 17:32 UTC, MaksimMelnik commented on examples/NO_Streicher.m
Теперь все циклы по всем возможным вариантам пробегают

2023-07-12 17:46 UTC, MaksimMelnik requested changes

2023-07-12 17:46 UTC, MaksimMelnik commented on examples/NO_Streicher.m
Меня сильно смущает, что гитхаб не показывает этот файл. Это не очень хорошо, что нельзя просто на сайте посмотреть. При этом он по длине он на 40 строк длиннее тест кейса с CO, но весит в 4 раза больше. Можешь попробовать исправить это? Может, что-то с кодировками? У меня Notepad++ без преобразования в UTF-8 не открывает текст тоже.

2023-07-12 17:46 UTC, MaksimMelnik commented on examples/O2_Ar_SW_Streicher.m
Этот тест кейс теперь тоже совсем не отображается. Весит также в 4 раза больше примера с CO. Так ещё и изменения не получается отследить. Можешь попробовать его тоже сделать читабельным гитхобом?

2023-07-12 19:30 UTC, MaksimMelnik approved these changes

2023-07-12 19:43 UTC, merged