Refl sw2.0
MaksimMelnik/STS-Simple-Solver pull request #7
Opened 2023-09-25 11:16 UTC by FlezZz23

Global: added a script for calculating the NO/N2/Ar mixture, as well as a script for plotting graphs. Convenient switchers have been added to display the necessary plots. Replacing R_exch with a new version

2023-09-25 12:13 UTC, MaksimMelnik requested changes

2023-09-25 12:13 UTC, MaksimMelnik commented on examples/N2_NO_Streicher.m
> +for i_ini=9
Нужно добавить под комментарием пробегание по всем тк (см. Шаталова)

2023-09-25 12:13 UTC, MaksimMelnik commented on examples/N2_NO_Streicher.m
> +for i_U=2 %choosing desired U dissociation parameter model
тоже добавить пробегание по U

2023-09-25 12:13 UTC, MaksimMelnik commented on examples/N2_NO_Streicher.m
> +for i_vibr=2 % choosing desired vibrational energy exchange model
пробегание по модели колебаний

2023-09-25 12:13 UTC, MaksimMelnik commented on examples/N2_NO_Streicher.m
Файл не вписан в ширину матлаба

2023-09-25 12:13 UTC, MaksimMelnik commented on examples/N2_NO_Streicher.m
> +    Ps={num, NO, O, N, O2, N2, Ar};
Может, аргон убирать из смеси, когда его нет?

2023-09-25 12:13 UTC, MaksimMelnik commented on examples/N2_NO_Streicher.m
> +    Reacs_keys={'Diss', 'VT','VV'}; %dissociation between
Диссоциацию можно убрать, если она не влияет между волнами

2023-09-25 12:13 UTC, MaksimMelnik commented on examples/N2_NO_Streicher.m
> +    TTT(i_ini)=timewave*1e6;
Это переменная нужна?

2023-09-25 12:13 UTC, MaksimMelnik commented on examples/N2_NO_Streicher.m
> +    dat1(i_vibr,i_U,i_ini,rel)=resSt_1;
Попробуй инициализировать dat и dat1 через struct() перед циклами, чтобы размер массива структур не менялся на каждом витке каждого цикла

2023-09-25 12:13 UTC, MaksimMelnik commented on examples/N2_NO_Streicher.m
> +    dat1(i_vibr,i_U,i_ini,rel)=resSt_1;
Попробуй инициализировать dat и dat1 через struct() перед циклами, чтобы размер массива структур не менялся на каждом витке каждого цикла

2023-09-25 12:13 UTC, MaksimMelnik commented on examples/NO_Streicher.m
Функция не работает.

2023-09-25 12:13 UTC, MaksimMelnik commented on examples/NO_Streicher.m
Также индексы в циклах должны указывать сначала только на одну комбинацию моделей для одного тк, как мы обсуждали раньше. А под комментарием весь набор параметров, по которому цикл может пробежать.

2023-09-25 12:25 UTC, FlezZz23 commented on data/reactions.mat
Хотя по-моему, они появились в мейне уже после того как я от него отбранчевался, а у меня они появились когда я сливался с твоей веткой по заряду. Поэтому он наверное думает что это разные файлы

2023-09-25 12:39 UTC, FlezZz23 commented on examples/N2_NO_Streicher.m
> +    Ps={num, NO, O, N, O2, N2, Ar};
Не думаю, что это имеет смысл, придется просто по всему коду добавить кучу if с проверкой есть ли сейчас аргон в смеси или нет. В чем смысл, если когда его нет, там просто везде 0, ну это наверное ускорит расчет, но я думаю это экономия на спичках

2023-09-25 13:06 UTC, MaksimMelnik commented on examples/N2_NO_Streicher.m
> +    Ps={num, NO, O, N, O2, N2, Ar};
В старой версии кода ещё до публикации тут я в задаче о CO пробовал убирать Ar, и прирост скорости был ощутимый. Я уже говорил об этом, кажется.
Ифы расставить нужно в мейн файле имеешь в виду? 
if based programming

2023-09-25 13:14 UTC, FlezZz23 commented on examples/N2_NO_Streicher.m
> +    Ps={num, NO, O, N, O2, N2, Ar};
ну да, там где везде фигурирует числовая плотность аргона придется поставить if

2023-09-25 13:17 UTC, MaksimMelnik commented on examples/N2_NO_Streicher.m
> +    Ps={num, NO, O, N, O2, N2, Ar};
И это не заменяется одним ифом в начале, что если нет аргона, то nAr=0 просто?

2023-09-25 13:37 UTC, FlezZz23 commented on examples/N2_NO_Streicher.m
> +    Ps={num, NO, O, N, O2, N2, Ar};
Частично, но несколько if придется еще добавить

2023-09-25 13:38 UTC, FlezZz23 commented on examples/N2_NO_Streicher.m
> +    Reacs_keys={'Diss', 'VT','VV'}; %dissociation between
Не стоит, если ее убрать это может создавать ошибки для обменных реакций после отраженной УВ, т.к. там не будет атомов О и N

2023-09-25 13:55 UTC, FlezZz23 commented on examples/N2_NO_Streicher.m
> +    Reacs_keys={'Diss', 'VT','VV'}; %dissociation between
Сейчас не вылетают ошибки, но когда-то (не помню точно когда, возможно для одной из моделей) вылетала ошибка в коэффициентах FHO, т.к. из-за того что не было диссоциации между волнами, то n_O=n_N=0 и там потоки в обменных реакциях в начальные моменты времени странно себя вели. Сейчас такого нет, но я оставлял включенным диссоциацию, даже если она слабо влияет. Поэтому не знаю в чем резон ее отключать

2023-09-25 14:06 UTC, MaksimMelnik commented on examples/N2_NO_Streicher.m
> +    Reacs_keys={'Diss', 'VT','VV'}; %dissociation between
Нужно попробовать разобраться в ошибке. Можешь попробовать тогда убрать диссоциацию и попробовать повторить ошибку? Как она возникнет, посмотрим на причины и что можно с этим сделать.

2023-09-25 16:08 UTC, MaksimMelnik requested changes

2023-09-25 16:08 UTC, MaksimMelnik commented on examples/N2_NO_Streicher.m
> +    %y0_1(kinetics.index{end})=Y(end, kinetics.index{end});
Этот код под комментарием ещё нужен?

2023-09-25 16:08 UTC, MaksimMelnik commented on examples/N2_NO_Streicher.m
Будет хорошо добавить больше комментариев, особенно не хватает подробнее в местах про обменные модели и их реализации

2023-09-25 16:08 UTC, MaksimMelnik commented on examples/N2_NO_Streicher.m
> +%save(['NO_N2_betweenSWs_withexch_avg.mat'], 'dat');
Сохранить лучше в папку output в корне, а не в папку примеров, потому что это сильно запутает

2023-09-25 16:08 UTC, MaksimMelnik commented on examples/NO_Streicher.m
> +%     NN=in_con_Ar([NO.mass, v0, T0, Ar.mass ,f]); %dimensionless variables
Этот код чеерз in_con_Ar ещё нужен?

2023-09-25 18:05 UTC, FlezZz23 commented on data/reactions_data_ini.m
> +react2.source = 'Kunova, NO(1)';
Заменил ее на модель Kunova, NO avg

2023-09-25 18:32 UTC, FlezZz23 commented on examples/N2_NO_Streicher.m
Имеешь ввиду в функциях Rexch и Rci или в основных скриптах с примерами?

2023-09-26 09:51 UTC, MaksimMelnik commented on examples/N2_NO_Streicher.m
В основных скриптах, когда ты выбираешь модели обмена: что ты выбираешь, из чего. Rexch ещё сильно переписываться будет, я боюсь

2023-09-26 10:55 UTC, MaksimMelnik requested changes
Нужно вернуть к универсальному состоянию весь внутренний код по химии, после этого смогу вернуться к основным файлам и заново их перепрогнать, после этого посмотреть скрипты для графиков

2023-09-26 10:55 UTC, MaksimMelnik commented on examples/NO_Streicher.m
>  %O2.num_vibr_levels=1;
код под комментарием

2023-09-26 10:55 UTC, MaksimMelnik commented on examples/NO_Streicher.m
Тоже добавь больше комментариев, пожалуйста, особенно около кода про обменные модели и их выбор

2023-09-26 10:55 UTC, MaksimMelnik commented on examples/N2_NO_Streicher.m
Добавь в описание ссылку на статью Страйкера, пожалуйста (см Шаталова https://github.com/MaksimMelnik/STS-Simple-Solver/blob/634fbfe98866faf6e9495e0b4893531e9918a0f9/examples/O2O_SW_Shatalov.m#L4)

2023-09-26 10:55 UTC, MaksimMelnik commented on examples/NO_Streicher.m
Добавь в описание ссылку на статью Страйкера, пожалуйста (см пример по Шаталову)

2023-09-26 10:55 UTC, MaksimMelnik commented on examples/NO_Streicher.m
>      T0=Y(end);
Можешь заменить in_con_Ar на in_con_SW тут, пожалуйста? И проверить, что после замены корректно пересчитывает. Хочу удалить устаревшие функции

2023-09-26 10:55 UTC, MaksimMelnik commented on examples/O2_Ar_SW_Streicher.m
> +for i_ini=1:9 % [1 2 3 4 5 6 7 8 9] % choosing desired initial coonditions
Здесь нужно оставить один наиболее иллюстративный тк и параметры моделей выбрать как в рекомендациях

2023-09-26 10:55 UTC, MaksimMelnik commented on examples/O2_Ar_SW_Streicher.m
> +%     if f==1
код под комментариями можно убрать?

2023-09-26 10:55 UTC, MaksimMelnik commented on examples/O2_Ar_SW_Streicher.m
> +    PPP(i_ini)=p_1(1);
Эти переменные ещё нужны?

2023-09-26 10:55 UTC, MaksimMelnik commented on src/R_exch.m
> +M3.num_vibr_levels=38;
M3 не должна объявляться внутри

2023-09-26 10:55 UTC, MaksimMelnik commented on src/R_exch.m
> +M3.num_vibr_levels=38;
M3 не должна объявляться внутри

2023-09-26 10:55 UTC, MaksimMelnik commented on src/Rci.m
> +
Код под комментарием можно убрать?

2023-09-26 10:55 UTC, MaksimMelnik commented on src/Rci.m
> + case "Kunova, NO avg"
Осреднение нужно вынести из Rci

2023-09-26 10:57 UTC, FlezZz23 commented on examples/NO_Streicher.m
я же уже добавил

2023-09-26 11:03 UTC, FlezZz23 commented on src/R_exch.m
> +M3.num_vibr_levels=38;
Хорошо, что предлагаешь сделать?

2023-09-26 11:03 UTC, FlezZz23 commented on src/Rci.m
> + case "Kunova, NO avg"
Каким образом?

2023-09-26 11:20 UTC, FlezZz23 commented on examples/O2_Ar_SW_Streicher.m
> +%     if f==1
убрал, функции in_con_Ar заменил на in_con_SW

2023-09-26 11:22 UTC, FlezZz23 commented on src/R_exch.m
> +M3.num_vibr_levels=38;
Можно объявить ее внутри функции Heaviside с проверкой если это NO, других вариантов пока не вижу

2023-09-26 14:23 UTC, MaksimMelnik requested changes

2023-09-26 14:23 UTC, MaksimMelnik commented on data/reactions_data_ini.m
> +react2.source = 'Kunova, NO(1)';
осталось NO(1) и тип Аррениус

2023-09-26 14:23 UTC, MaksimMelnik commented on src/R_exch.m
> +M3.num_vibr_levels=38;
Делаем под switch новый тип, в нём подгружаем информацию об NO, из R_exch_Heaviside вытаскиваем только kf и в этом кейсе свитча вручную считаем dE, Kfb, R_exch

2023-09-26 14:23 UTC, MaksimMelnik commented on src/R_exch.m
> +if VDOP==0
минимизировать ифы, постараться их вынести из этой функции вверх под свитч, чтобы модель Савельева с Хевисайдом осталась неизменённая, как в его статье. А все метаморфозы над ней были бы выше.

2023-09-26 14:23 UTC, MaksimMelnik commented on src/Rci.m
> + case "Kunova, NO avg"
спустить вниз в R_exch под свитч

2023-09-26 14:23 UTC, MaksimMelnik commented on examples/N2_NO_Streicher.m
> +for i_exch=2 % [1 2 3]
i_exch=3 ошибка

2023-09-26 14:46 UTC, MaksimMelnik commented on examples/N2_NO_Streicher.m
Пустые строки не нужно добавлять, так разрывается описание функции

2023-09-26 15:02 UTC, MaksimMelnik commented on examples/N2_NO_Streicher.m
> +    %IMPORTANT: if you run calculations with different exchange models,
А вот это плохо, из-за этого могут быть ошибки. Стоит добавить какой-то код для избегания запуска i_exch=1,2, когда спектр NO обрезан. Можно, например,  сразу после "for i_exch= ..." прописать load(particles, NO)

2023-09-26 15:08 UTC, MaksimMelnik commented on examples/N2_NO_Streicher.m
> +    Reacs_keys={'VT','VV'}; %dissociation between
комментарий не закончен

2023-09-26 15:16 UTC, MaksimMelnik commented on examples/N2_NO_Streicher.m
> +        disp("Error, invalid value of i_exch");
лучше использовать error("invalid value of i_exch"), чтобы код не бежал дальше

2023-09-27 16:09 UTC, FlezZz23 commented on examples/N2_NO_Streicher.m
> +for i_exch=2 % [1 2 3]
Там были структуры разных типов из-за того что изначально в структуре есть поле TvNO, а в случае i_exch=3 этого поля нет, исправил

2023-09-27 16:10 UTC, FlezZz23 commented on src/R_exch.m
> +if VDOP==0
Сделал эту систему, как мы обсуждали

2023-09-27 16:10 UTC, FlezZz23 commented on examples/N2_NO_Streicher.m
> +    %IMPORTANT: if you run calculations with different exchange models,
Добавил подгрузку NO после цикла для i_exch

2023-09-28 10:29 UTC, MaksimMelnik requested changes
Продолжу смотреть остальной код, когда R_exch вернётся в универсальное состояние

2023-09-28 10:29 UTC, MaksimMelnik commented on src/R_exch.m
>  M3.ev_0(1)=1.8843e-20;
M3 всё ещё объявляется внутри R_exch

2023-09-28 10:56 UTC, FlezZz23 commented on src/R_exch.m
>  M3.ev_0(1)=1.8843e-20;
Виноват, убрал и еще также убрал лишний закомментированный код

2023-09-28 12:40 UTC, MaksimMelnik commented on examples/N2_NO_Streicher.m
Все пустые строки в описании

2023-09-28 12:40 UTC, MaksimMelnik commented on examples/NO_Streicher.m
Все пустые строки в описании

2023-09-28 13:41 UTC, MaksimMelnik requested changes

2023-09-28 13:41 UTC, MaksimMelnik commented on src/R_exch.m
> +  coll.ArrE = reaction.E / k;   % in K
k не существует. Нужно исправить и перепроверить ещё раз, что R_exch работает и не выдаёт ошибок

2023-10-02 19:22 UTC, MaksimMelnik requested changes
Извини, что не успел посмотреть изменения на выходных, не хватило времени. Нашёл баг, связанный с инициализацией индексов. Странно, что он только сейчас всплыл. Во всех мейнах переписал индексы по подобию примера по Шаталову.
Прогнал скрипты графиков, увидел много багов. Включал везде все свитчеры для графиков. Перечислил ниже всё, что нашёл. 
Я прошу тебя запускать все скрипты по всем параметрам как раз потому, что они так легко всплывают. Если ты будешь всё же прогонять весь код перед пушем в ветку, то сам обнаружишь большую часть ошибок и процесс дебага пойдёт быстрее, чем через второго человека (меня в нашем случае).
Весь код по вычислениям вроде бы хорошо всё считает, кроме странных артефактов у VDF (см ниже). Так что как будто бы осталось исправить перечисленные баги, старые замечания и можно заканчивать. 
Единственное, надо сначала замерджить сюда мейн ветку, похоже, потому что сейчас гитхаб прям показывает конфликты с ней. Надеюсь, это будет быстро.

2023-10-02 19:22 UTC, MaksimMelnik commented on plots/Streicher22_NO_plots.m
> +load('..\data\NO Streicher experiment\NO_behind_ReflSW_output.mat');
имя аутпута расходится с мейн файлом

2023-10-02 19:22 UTC, MaksimMelnik commented on plots/Streicher22_NO_plots.m
В статье был же график для давления? Ты его рисовал? Не нашёл его в скрипте.

2023-10-02 19:22 UTC, MaksimMelnik commented on plots/Streicher22_NO_plots.m
Для 9го тесткейса на картинке VDF странное волнистое распределение в момент времени 0. Почему так получается, не хватает точности для расчёта между волнами?

2023-10-02 19:22 UTC, MaksimMelnik commented on plots/Streicher22_NO_plots.m
Тесткейсы 2, 7 и 11 вылетают на 397 строке с ошибкой

2023-10-02 19:22 UTC, MaksimMelnik commented on plots/Streicher22_NO_plots.m
На Figure 2 легенды не хватает, чтобы понять отрисованные кривые. Эта фигура вообще актуальная или для тестов рисовалась?

2023-10-02 19:22 UTC, MaksimMelnik commented on plots/Streicher22_NO_plots.m
У тест кейсов 5 и 6 получаются оборванные VDF в нулевой момент времени? Может ли это тоже быть связано с недостаточной точностью счёта между волнами или дело в другом?

2023-10-02 19:22 UTC, MaksimMelnik commented on plots/Streicher22_NO_N2_plots.m
> +%testcases
Описание тест кейсов не соответствует мейн файлу и эксперименту

2023-10-02 19:22 UTC, MaksimMelnik commented on plots/Streicher22_NO_N2_plots.m
> +%VDF_O2N2_plot - plot VDF for N2 and O2
Включение свитчера VDF_O2N2_plot выдаёт ошибку

2023-10-02 20:28 UTC, FlezZz23 commented on plots/Streicher21_O2_Ar_plots.m
Нет конечно, в качестве data_main выбираешь другую модель и будут графики для новой модели. Если необходимо будет сравнить две модели, то придется добавить data_minor по аналогии с другими скриптами (для NO), но у нас не было такой необходимости для кислорода, поэтому этого нет

2023-10-02 20:28 UTC, FlezZz23 commented on plots/Streicher21_O2_Ar_plots.m
> +P_plot=false;
Да, этих данных нет, видимо не тот массив данных, либо я не стал снимать давление за ненадобностью

2023-10-02 21:12 UTC, FlezZz23 commented on plots/Streicher22_NO_plots.m
Может быть

2023-10-02 21:18 UTC, FlezZz23 commented on plots/Streicher22_NO_plots.m
легенду дополнил, а вообще да это фигура со сравнением n_NO для двух моделей

2023-10-02 21:22 UTC, FlezZz23 commented on plots/Streicher22_NO_plots.m
Если взять момент времени чуть больше чем нулевой, например вызвать не ni_NO(1,:), а ni_NO(3, :), что соответствует 0.04 мкс, то не будет обрываться, так что полагаю это связано с недостаточной точностью и заселенность стабилизируется через несколько итераций

2023-10-02 21:24 UTC, FlezZz23 commented on plots/Streicher22_NO_N2_plots.m
> +%testcases
Я думаю это вообще можно убрать, описание экспериментов есть в переменной info

2023-10-02 22:18 UTC, FlezZz23 commented on plots/Streicher22_NO_plots.m
Иногда попадаются артефакты связанные со странным поведением распределения в начальный момент времени, завтра попробую проверить лечиться ли это повышение точности расчета

2023-10-03 08:10 UTC, MaksimMelnik commented on plots/Streicher21_O2_Ar_plots.m
Можешь тогда чуть более подробно в файлах расписать алгоритм сравнения, как для не работающих с этим кодом людей? 
Для O2 я боюсь, что нужно добавить возможность сравнить с чем-то. Так как мы в статьях даём рекомендации, то при анализе новых моделей хорошо сравнивать их не только с экспериментом, но ещё и с рекомендованной комбинацией. Это потому, что у нас модели иногда где-то да вылетают, и мы при выработке рекомендаций выбирали меньшее из зол. 

Также вопрос: при добавлении новой модели легенды тоже можно быстро изменить или нужно каждую править вручную?

2023-10-03 08:13 UTC, MaksimMelnik commented on plots/Streicher21_O2_Ar_plots.m
> +P_plot=false;
Мне кажется, лучше снять и добавить данные по давлению. Без него можно подумать, что мы не учитывали его график при анализе, и возникают вопросы к его полноте.

2023-10-03 08:14 UTC, MaksimMelnik commented on plots/Streicher22_NO_plots.m
А он у тебя не остался где-нибудь вернуть в этот скрипт?

2023-10-03 08:16 UTC, MaksimMelnik commented on plots/Streicher22_NO_N2_plots.m
> +%testcases
Смотреть на текст под комментарием гораздо удобнее, чем вызывать переменную, на самом деле.

2023-10-03 12:11 UTC, FlezZz23 commented on plots/Streicher21_O2_Ar_plots.m
Могу добавить if на data_minor чтоб это было по желанию, но вообще я планировал просто везде добавить графики с data_minor и добавить их в легенду, если у пользователя нет надобности сравнивать две модели то можно их выбрать одинаковыми и легенду подправить вручную

2023-10-03 12:12 UTC, FlezZz23 commented on plots/Streicher22_NO_plots.m
Вряд ли остался. В анализе для NO мы его не учитывали никак, смысл его возвращать?

2023-10-03 12:28 UTC, FlezZz23 commented on plots/Streicher21_O2_Ar_plots.m
> +P_plot=false;
Добавил

2023-10-03 17:37 UTC, FlezZz23 commented on plots/Streicher22_NO_plots.m
> +load('..\data\NO Streicher experiment\NO_behind_ReflSW_output.mat');
исправил

2023-10-04 10:07 UTC, MaksimMelnik commented on plots/Streicher21_O2_Ar_plots.m
А когда ты планировал это сделать?

2023-10-04 11:50 UTC, FlezZz23 commented on plots/Streicher21_O2_Ar_plots.m
А я так и не понял, мне создать шаблон для сравнения в кислороде или что? Просто в кислороде нам нечего сравнивать

2023-10-04 14:30 UTC, FlezZz23 commented on plots/Streicher21_O2_Ar_plots.m
Добавил data_minor и пока запихнул туда основные данные и добавил комментарий, что если будет новая модель то заменить эти данные на новую модель

2023-10-04 20:38 UTC, MaksimMelnik requested changes
Всплыл баг с энергиями в O2 (там не только в одной комбинации вылет зс) и VDF ломаются. С VDF то ли Матлаб что-то путает, то ли что-то там есть проблемное -- не понятно. Но нужно проверить, чтобы не упустить какого вредного бага.

2023-10-04 20:38 UTC, MaksimMelnik commented on plots/Streicher22_NO_N2_plots.m
оборвана VDF в начальный момент времени в тк 4, 10. Похоже как на графики для NO без N2. Причём вектор заселённостей нормальный вроде бы, без артефактов, хотя график ломается.

2023-10-04 21:35 UTC, FlezZz23 commented on examples/O2_Ar_SW_Streicher.m
Исправил, разница была в том что после отраженной обезразмеривание производилось с параметром f=1, хотя за время между волнами относительное количество молекул кислорода уменьшилось

2023-10-04 21:37 UTC, FlezZz23 commented on examples/NO_Streicher.m
>      timewave=1000*1e-6;
просто без комментариев. оставлю комментарий чтоб пользователь мог сам ввести нужный промежуток

2023-10-04 21:49 UTC, FlezZz23 commented on plots/Streicher22_NO_N2_plots.m
в тесткейсе 4 не вижу никакой поломки, в тесткейсе 10 на уровне 25 обрыв, ибо там заселенность почему-то обнулялась. Пересчитал с более точными параметрами, обрыв пропал. Поэтому это связано с точностью расчета, не думаю что тут, что-то серьезное

2023-10-04 22:34 UTC, FlezZz23 commented on plots/Streicher22_NO_N2_plots.m
Поставил значения точности 1e-11 и 1e-13, долго считал, но кажется это устраняет обрывы

2023-10-06 21:02 UTC, MaksimMelnik commented on plots/Streicher22_NO_plots.m
Выяснили всё таки, что это из-за недостатка точности. Давай тогда повышать точность для расчёта между волнами, для за отражённой вроде как пока хватает точности.

2023-10-06 21:05 UTC, FlezZz23 commented on plots/Streicher22_NO_plots.m
Так я вернул нулевой момент времени, в скрипт с графиками NO, расчет более точный уже проводил, что еще сделать то

2023-10-06 21:07 UTC, MaksimMelnik requested changes
Нужно тогда повысить точность между волнами, чтобы убрать артефакты VDF. Кроме этого дополнить гитигнор, закончить с комментариями по оформлению, уменьшить длину интегрирования за отражённой NO для ускорения, и можно влить сюда мейн, будем разрешать конфликты. Надеюсь, там не будет больших проблем с этими конфликтами.

2023-10-06 21:09 UTC, MaksimMelnik commented on plots/Streicher22_NO_plots.m
В смысле проставь в мейн файлах NO достаточную точность между волнами, чтобы артефакты VDF ушли. Ты говорил, что подобрал её, но не внёс эти значения в репозиторий.

2023-10-06 21:19 UTC, FlezZz23 commented on plots/Streicher22_NO_plots.m
Запушил новую точность и уменьшил длины промежутков расчета, не понял что еще надо в гитигнор добавить и какие остались комментарии по оформлению нерешенные?

2023-10-07 10:08 UTC, MaksimMelnik commented on plots/Streicher22_NO_plots.m
В гитигнор файлы расчётов между волнами, комментарии по оформлению -- где неразрешённые замечания к файлам. Не закрывай обсуждения сам, пожалуйста, я просил этого не делать. Там выравнивание, разорванные описания мейн файлов и устаревший код под комментарием.

2023-10-10 13:29 UTC, MaksimMelnik approved these changes

2023-10-13 19:58 UTC, merged